version: "3.7"

x-common-variables: &common-variables
  eureka.client.serviceUrl.defaultZone: http://eureka:8080/eureka
  eureka.instance.non-secure-port: 8080

services:
  eureka:
    image: "dhananjay12/cqrs-eureka-server:latest"
    environment:
      <<: *common-variables
    ports:
      - "8761:8080"
  gateway:
    image: "dhananjay12/cqrs-gateway:latest"
    environment:
      <<: *common-variables
    ports:
      - "8080:8080"
  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    volumes:
      - ./axon-data/data:/data
      - ./axon-data/eventdata:/eventdata
      - ./axon-data/config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
